<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>fc9d8db5-1315-4c5f-a12d-326d14e95a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification-request']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Continue&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc7e69f3-ed9b-4d4f-a243-7776dc58358f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>f1513318-9c15-4dfb-82bb-d51ef2d26943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>b28801ea-30c5-4a2f-bb2f-57bc63be1020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification-request&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;ok&quot;]</value>
      <webElementGuid>a8d9dde0-6eff-447d-8292-492a66b5ec53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification-request']/div/div[2]</value>
      <webElementGuid>311922e4-b5a4-4ecb-8ebb-9179889ccc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rework.com'])[1]/following::div[1]</value>
      <webElementGuid>10f11aa9-eedf-4f8f-b467-b5ac8d960fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/preceding::div[19]</value>
      <webElementGuid>0ae197e5-b0b5-4ec2-b703-ff262049235f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[23]</value>
      <webElementGuid>75ed4695-af69-494d-b0c4-199029c87761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>97e7de86-cba7-442c-98ff-d35c3334454d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]</value>
      <webElementGuid>960b8338-7c77-470f-b0d3-9096a0cb1627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>4e672f7a-101c-4fa7-905e-cf021c5dcdcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
